apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  clusterIP: 10.98.28.252
  externalTrafficPolicy: Cluster
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
