apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  clusterIP: 10.101.198.252
  externalTrafficPolicy: Cluster
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: client
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
